version: '4'

services:
  main:
    image: php:8-phpake
    container_name: phpake
    build:
      context: .
      dockerfile: .docker/main/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/app
